#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)

clear
domain=$(cat /etc/xray/domain)
masaaktif=1
Quota=1
iplimit=10
user=Trial-VL`</dev/urandom tr -dc 0-9 | head -c3`
clear 
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e " Settings Tittle Triall         "
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e ""
echo -e ""
echo -e "\033[1;96m___________________________________________\033[0m"
read -p " Menit : " pup
echo -e "\033[1;96m___________________________________________\033[0m"
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
clear
vlesslink1="vless://${uuid}@${domain}:443?encryption=none&security=tls&sni=${domain}&type=ws&host=${domain}&path=%2Fvless#${user}-WS-TLS"
vlesslink2="vless://${uuid}@${domain}:80?encryption=none&security=none&type=ws&host=${domain}&path=%2Fvless#${user}-WS-NTLS"
vlesslink3="vless://${uuid}@${domain}:443?encryption=none&security=tls&sni=${domain}&type=grpc&serviceName=vless-grpc&mode=gun#${user}-gRPC"
cat >/var/www/html/vless-$user.txt <<-END

====================
BY FAHRI ALIMUDIN
082328013583
====================

# Format Vless WS TLS

proxies:
  - name: Vless-$user-WS TLS
    server: ${domain}
    port: 443
    type: vless
    uuid: ${uuid}
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ${domain}
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: ${domain}
    udp: true

# Format Vless WS Non TLS

proxies:
  - name: Vless-$user-WS (CDN) Non TLS
    server: ${domain}
    port: 80
    type: vless
    uuid: ${uuid}
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: ${domain}
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: ${domain}
    udp: true
    
# Format Vless Grpc

proxies:
  - name: Vless-$user-WS (CDN) gRPC (SNI)
    server: ${domain}
    port: 443
    type: vless
    uuid: ${uuid}
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ${domain}
    network: grpc
    grpc-opts:
      grpc-service-name: vless-grpc
    udp: true

====================
Link Akun Vless 
====================
Link TLS      : 
${vlesslink1}
====================
Link none TLS : 
${vlesslink2}
====================
Link GRPC     : 
${vlesslink3}
====================


END

systemctl restart xray
systemctl restart nginx
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vless/ip
echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^#&" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "#& ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db
clear
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "    TRIALL VLESS          "
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Remarks     : ${user}"
echo -e "Domain      : ${domain}"
echo -e "User Quota  : ${Quota} GB"
echo -e "port TLS    : 443, 8443, 2087, 2096"
echo -e "Port NTLS   : 80, 8080, 8880, 2082"
echo -e "User ID     : ${uuid}"
echo -e "Encryption  : none"
echo -e "Path TLS    : /vless "
echo -e "ServiceName : vless-grpc"
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Link TLS    : ${vlesslink1}"
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Link NTLS   : ${vlesslink2}"
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Link GRPC   : ${vlesslink3}"
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Format OpenClash : https://${domain}:81/vless-$user.txt"
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Aktif Selama     : $pup menit"
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e ""
echo "tunnel vless ${user}" | at now +$pup minutes &> /dev/null
read -n 1 -s -r -p "Press any key to back on menu"
menu
