#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)

clear
domain=$(cat /etc/xray/domain)
masaaktif=1
Quota=1
iplimit=10
user=Trial-TR`</dev/urandom tr -dc 0-9 | head -c3`
clear
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e " Set Expired In Minutes           "
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m"
read -p " Menit : " pup
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
# Link Trojan Akun
systemctl restart xray
trojanlink1="trojan://${uuid}@${domain}:443?security=tls&sni=${domain}&type=grpc&serviceName=trojan-grpc&mode=gun#${user}-gRPC"
trojanlink="trojan://${uuid}@${domain}:443?security=tls&sni=${domain}&type=ws&host=${domain}&path=%2Ftrojan-ws#${user}-WS"

cat >/var/www/html/trojan-$user.txt <<-END
====================
BY FAHRI ALIMUDIN
082328013583
====================

# Format Trojan GO/WS

proxies:
  - name: Trojan-$user-GO/WS
    server: ${domain}
    port: 443
    type: trojan
    password: ${uuid}
    skip-cert-verify: true
    sni: ${domain}
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: ${domain}
    udp: true

# Format Trojan gRPC

proxies:
  - name: Trojan-$user-gRPC
    server: ${domain}
    port: 443
    type: trojan
    password:  ${uuid}
    skip-cert-verify: true
    sni: ${domain}
    network: grpc
    grpc-opts:
      grpc-service-name: trojan-grpc
    udp: true

====================
Link Akun Trojan 
====================
Link WS          : 
${trojanlink}
====================
Link GRPC        : 
${trojanlink1}
====================

END

service cron restart
trojanlink="trojan://${uuid}@${domain}:443?security=tls&sni=${domain}&type=ws&host=${domain}&path=%2Ftrojan-ws#${user}-WS"
trojanlink1="trojan://${uuid}@${domain}:443?security=tls&sni=${domain}&type=grpc&serviceName=trojan-grpc&mode=gun#${user}-gRPC"
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/trojan/ip
echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
clear
echo -e ""
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e " TRIALL TROJAN        "
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Remarks          : ${user}" 
echo -e "Host/IP          : ${domain}"
echo -e "User Quota       : ${Quota} GB"
echo -e "User IP          : ${iplimit} IP"
echo -e "port             : 400-900" 
echo -e "Key              : ${uuid}" 
echo -e "Path             : /trojan-ws" 
echo -e "ServiceName      : trojan-grpc" 
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Link WS          : ${trojanlink}" 
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Link GRPC        : ${trojanlink1}" 
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Format OpenClash : https://${domain}:81/trojan-$user.txt" 
echo -e "\033[1;96m___________________________________________\033[0m"
echo -e "Aktif Selama     : $pup menit"
echo -e "\033[1;96m___________________________________________\033[0m"
echo "tunnel trojan ${user}" | at now +$pup minutes &> /dev/null
echo "" 
read -n 1 -s -r -p "Press any key to back on menu"
menu
